config/routes.rb
Rails.application.routes.draw do

  # get 'empleados/index'

  # get 'empleados/new'

  # get 'empleados/show'

  # get 'empleados/update'

  # get 'empleados/destroy'

  # get 'sucursales/index'
  # get 'sucursales/'

  # get 'sucursales/new'

  # get 'home/index'

  devise_for :users
	root to: "sucursales#index"
  resources :sucursales
	resources :empleados
	# resources :home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empleado.rb
class Empleado < ApplicationRecord
	validates :nombre, :presence => {:message => "No puedes dejar el nombre del empleado vacio" }
	validates :rfc, :presence => {:message => "No puedes dejar el RFC del empleado vacio" }
  	belongs_to :sucursal, optional: true
  	has_one	:sucursal

  	# Se crea metodo para buscar
  	def self.buscar_por_sucursal(sucursal_id)
		where(:sucursal_id => sucursal_id)
	end



end

app/models/sucursal.rb
class Sucursal < ApplicationRecord
	validates :nombre, :presence => {:message => "No puedes dejar el nombre de la sucursal vacio" }
	validates_numericality_of :numExt, :only_integer => true, :allow_nil => true, :message => "Tiene que ser un numero"
	validates_numericality_of :numInt, :only_integer => true, :allow_nil => true, :message => "Tiene que ser un numero"
	validates_numericality_of :cp, :only_integer => true, :allow_nil => true, :message => "Tiene que ser un numero"
	has_many :empleados, :foreign_key => "sucursal_id", :dependent => :destroy
	accepts_nested_attributes_for :empleados, allow_destroy: true, reject_if: :all_blank
	belongs_to :user 

	


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # attr_accessor :nombre
  validates :nombre, :email, :empresa, :rfc, :encrypted_password, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sucursal, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nombre,:empresa,:rfc])
  end

end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def new
    @empleado = Empleado.new
    @sucursalesDisp = Sucursal.where(user_id: current_user.id)

    
  end

  def edit
      @empleado       = Empleado.find(params[:id])
      @suc            = Sucursal.where('id': @empleado.sucursal_id)
      @sucursalesDisp = Sucursal.where(user_id: current_user.id)
    end

  def show
  end

  def create
    @empleado = Empleado.new
    @sucursalesDisp = Sucursal.where(user_id: current_user.id)
    # Se revisa si hay cupo para el nuevo empleado en la sucursal
    if  !params[:empleado][:sucursal_id].present?
      @error = "No se selecciono ninguna sucursal";
      redirect_to new_empleado_path, notice: "No se selecciono ninguna sucursal"
    else
      @cupo = Empleado.where('sucursal_id': params[:empleado][:sucursal_id].to_i).count
      if @cupo >= 5 
        flash[:notice] = "La sucursal seleccionada ya tiene 5 empleados"
        redirect_to new_empleado_path
      else
        @empleado = Empleado.new(parametros) 
        if @empleado.save
          redirect_to sucursale_path(@empleado.sucursal_id)
        else
          render 'new'
        end
      end
    end
  end

  def update
      @empleado = Empleado.find(params[:id])
      # byebug
      # Se esta actualizando informacion de un empleado existente en la sucursal
      if @empleado.sucursal_id == params[:empleado][:sucursal_id].to_i
        if @empleado.update(parametros)
          redirect_to sucursale_path(@empleado.sucursal_id)
        else
          @sucursalesDisp = Sucursal.where(user_id: current_user.id)
          @suc            = Sucursal.where('id': @empleado.sucursal_id)
          render 'edit'
        end
      else
        # Se esta actualizando un empleado desde otra sucursal, hay que validar
        @cambio = Empleado.where('sucursal_id': params[:empleado][:sucursal_id].to_i).count
        if @cambio >= 5 
          @suc            = Sucursal.where('id': @empleado.sucursal_id.to_i)
          @sucursalesDisp = Sucursal.where(user_id: current_user.id)
          @error = "La sucursal seleccionada ya tiene 5 empleados"
          render 'edit'
          # byebug
        else
          if @empleado.update(parametros)
            # byebug
            redirect_to sucursale_path(@empleado.sucursal_id)
          else
            render 'edit'
          end
        end
      end
    end

  def destroy
      @empleado = @sucursal = Empleado.find(params[:id])
      @empleado.destroy
      redirect_to sucursale_path(@sucursal.sucursal_id)
  end

  private

    def parametros
      params.require(:empleado).permit(:nombre,:rfc,:puesto,:sucursal_id)
      
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	# Valida si el usuario esta logeado antes de dejarlo entrar a los metodos del sistema
  	before_action :authenticate_user!

  	# Muestra el panel principal de la aplicacion
  def index
  	@sucursal 	=  	Sucursal.where(user_id: current_user.id)
  	#@user 		=	current_user.email

  end

  def sucursales
  	@sucursal =  Sucursal.all
  end
end

app/controllers/sucursales_controller.rb
class SucursalesController < ApplicationController
	before_action :authenticate_user!
  	def index
  		
  		@sucursal =  Sucursal.paginate(:page => params[:page], :per_page => 10).where(user_id:current_user.id)

  	end

	def new
	  	@sucursal = Sucursal.new
	  	@sucursal.empleados.new
	  	# render 'new'
	end
	
	def create
		@sucursal = current_user.sucursal.new(parametros) 
		#byebug
		if @sucursal.save
			# Empleado.new(params[:empleados_attributes])
			redirect_to sucursales_path
		else
			render "new"
			
		end
	end
	
	def show
	  	@sucursal =  Sucursal.find(params[:id]);	
	  	@empleados = Empleado.buscar_por_sucursal(params[:id])
      # byebug
  	end
	
	def edit
	  	@sucursal =  Sucursal.find(params[:id]);
  	end

  	def update
  		@sucursal = Sucursal.find(params[:id])

  		if @sucursal.update(parametros)
  			redirect_to sucursale_path
  		else
  			render 'edit'
  		end
  		
  	end

  	def destroy
  		Sucursal.find(params[:id]).destroy
  		redirect_to sucursales_path
  	end

  private

  	def parametros
  		params.require(:sucursal).permit(:nombre, :colonia, :calle, :cp, :pais, :ciudad, :numInt, :numExt, empleados_attributes:[:nombre,:rfc,:puesto,:_destroy])
  		
  	end


end
# @empleado.empleados_percepciones.build

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sucursales_helper.rb
module SucursalesHelper
end

app/views/empleados/destroy.html.erb
<h1>Empleados#destroy</h1>
<p>Find me in app/views/empleados/destroy.html.erb</p>

app/views/empleados/edit.html.erb
<div class="col-md-12">
	<p>
		<h2>Empleado de sucursal</h2>
	</p>
	<% if @error %>
	<div class="alert alert-warning" role="alert"><h3><%= @error %></h3></div>
	<% end %>
		<%= form_for @empleado, url: {action: "update"}, html: {class: ""} do |e| %>
		<% if @empleado.errors.any? %>
			<div id="error_explanation">
			<h3>
				<%= pluralize(@empleado.errors.count, "error") %> no permitieron que se actualizara la informacion:
			</h3>
			<ul>
				<% @empleado.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
			</div>
		<% end %>
			<table class='table table-hover table-striped'>
				<tr>
					<th>Nombre</th>
					<td><%= e.text_field :nombre,	class: 'form-control' %></td>
				</tr>
				<tr>
					<th>RFC</th>
					<td>
						<input readonly="true" class="form-control" value="<%= @empleado.rfc %>">
					</td>
				</tr>
				<tr>
					<th>Puesto</th>
					<td><%= e.text_field :puesto,	class: 'form-control' %></td>
				</tr>
				<tr>
					<th>Sucursal</th>
					<td>
						<select name="empleado[sucursal_id]" class="form-control">
							<option value="<%= @empleado.sucursal_id %>" selected>
								<% @suc.each do |suc| %>
									<%= suc.nombre %>
								<% end %>
							
							</option>
							<% @sucursalesDisp.each do |li| %>
 								<option value="<%= li.id %>"><%= li.nombre %></option>
							<% end %>
						</select>
					</td>
				</tr>
			</table>
			<%= e.submit 'Actualizar informacion', :class => 'btn btn-info' %>
		<% end %>
</div>

app/views/empleados/index.html.erb
<h1>Empleados#index</h1>
<p>Find me in app/views/empleados/index.html.erb</p>

app/views/empleados/new.html.erb
<div class="col-md-12">
	<p>
		<h2>Crear empleado</h2>
	</p>
	<!-- <% flash.each do |key, value| %>
		<div class="alert alert-warning alert-dismissible"><%= value %></div>
	<% end %> -->
	
		<%= form_for @empleado, url: {action: "create"}, html: {class: ""} do |e| %>
		<% if @empleado.errors.any? %>
			<div id="error_explanation">
			<ul>
				<% @empleado.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
			</div>
		<% end %>
			<table class='table table-hover table-striped'>
				<tr>
					<th>Nombre</th>
					<td><%= e.text_field :nombre,	class: 'form-control' %></td>
				</tr>
				<tr>
					<th>RFC</th>
					<td><%= e.text_field :rfc,	class: 'form-control' %></td>
				</tr>
				<tr>
					<th>Puesto</th>
					<td><%= e.text_field :puesto,	class: 'form-control' %></td>
				</tr>
				<tr>
					<th>Sucursal</th>
					<td>
						<select name="empleado[sucursal_id]" class="form-control">
							<%= @sucursalesDisp.each do |li| %>
								<option value="<%= li.id %>"><%= li.nombre %></option>
							<% end %>
						</select>
					</td>
				</tr>
			</table>
			<%= e.submit 'Guardar Empleado', :class => 'btn btn-success' %>
		<% end %>
</div>

app/views/empleados/show.html.erb
<h1>Empleados#show</h1>
<p>Find me in app/views/empleados/show.html.erb</p>

app/views/empleados/update.html.erb
<h1>Empleados#update</h1>
<p>Find me in app/views/empleados/update.html.erb</p>

app/views/home/index.html.erb
<div class="container">
	<h1>Dashboard</h1>
    <ul>
    <% @sucursal.each do |s| %>
      <li><%= s.nombre %></li>
    <% end %>
    </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Examen</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>


  </head>
  
  <body>
   <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Devise Demo', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <%= current_user.email %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
<!--                   <li><%= link_to 'Profile', edit_user_registration_path %></li>
 -->                  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Log In', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

  <div class="container">
    <%= yield %>
  </div>
    <%= insert_paloma_hook %>
</html>


<script type="text/javascript">

  $(document).ready(function(){
    Paloma.start();
  });

</script>

app/views/sucursales/_sucursales_templates.html.erb
<table class='table'>
	<tr>	
		<th>Nombre</th>
		<td><input type="text" name="nombre" placeholder=""></td>
	</tr>
	<tr>	
		<th>Calle</th>
		<td><input type="text" name="nombre" placeholder=""></td>
	</tr>
	<tr>	
		<th>Colonia</th>
		<td><input type="text" name="nombre" placeholder=""></td>
	</tr>
	<tr>	
		<th>Num. Ext.</th>
		<td><input type="number" name="nombre" placeholder=""></td>
	</tr>
	<tr>	
		<th>Num. Int.</th>
		<td><input type="number" name="nombre" placeholder=""></td>
	</tr>
	<tr>	
		<th>C.P.</th>
		<td><input type="number" name="nombre" placeholder=""></td>
	</tr>
	<tr>	
		<th>Pais</th>
		<td><input type="text" name="nombre" placeholder=""></td>
	</tr>
	<tr>	
		<th>Ciudad</th>
		<td><input type="text" name="nombre" placeholder=""></td>
	</tr>
</table>

app/views/sucursales/edit.html.erb
<h1>Editar Sucursal</h1>
<div class="col-md-12">
	<%= form_for @sucursal, url: {action: "update"}, html: {class: ""} do |s| %>
	
	<% if @sucursal.errors.any? %>
		<div id="error_explanation">
		<h3>
			<%= pluralize(@sucursal.errors.count, "error") %> no permitieron que se actualizara la informacion:
		</h3>
		<ul>
			<% @sucursal.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
		</div>
	<% end %>

		<table class='table'>
			<tr>	
				<th>Nombre</th>
				<td><%= s.text_field :nombre,class: 'form-control' %></td>
			</tr>
			<tr>	
				<th>Calle</th>
				<td><%= s.text_field :calle,class: 'form-control' %></td>
			</tr>
			<tr>	
				<th>Colonia</th>
				<td><%= s.text_field :colonia,class: 'form-control' %></td>
			</tr>
			<tr>	
				<th>Num. Ext.</th>
				<td><%= s.number_field :numExt,class: 'form-control' %></td>
			</tr>
			<tr>	
				<th>Num. Int.</th>
				<td><%= s.number_field :numInt,class: 'form-control' %></td>
			</tr>
			<tr>	
				<th>C.P.</th>
				<td><%= s.number_field :cp,class: 'form-control' %></td>
			</tr>
			<tr>	
				<th>Pais</th>
				<td><%= s.text_field :pais,class: 'form-control' %></td>
			</tr>
			<tr>	
				<th>Ciudad</th>
				<td><%= s.text_field :ciudad,class: 'form-control' %></td>
			</tr>
		</table>
		<%= s.submit 'Actualizar informacion', :class => 'btn btn-info' %>
		<% end %>
	</div>

app/views/sucursales/index.html.erb
<style type="text/css">
.btnMains{
    margin-right: 10px;
}
</style>

<div class="container">
    <%= link_to "Nueva Sucursal", new_sucursale_path, id: "news", class: "btnMains btn btn-primary pull-right btn-md" %>

	<% if @sucursal.length > 0 %>
    	<%= link_to "Nuevo Empleado", new_empleado_path, id: "new", class: "btnMains btn btn-primary pull-right btn-md" %>
	<% end %>
	<h1>Sucursales</h1>

    <% if @sucursal.length > 0 %>
    	<table class="table table-hover table-striped">
    		<tr>
    			<th></th>
    			<th>Nombre</th>
    			<th>Calle</th>
    			<th>Codigo Postal</th>
    			<th>Pais</th>
    			<th>Ciudad</th>
    			<th></th>
    			<th></th>
    			<th></th>
    		</tr>
		    <% @sucursal.each do |s| %>
		      <tr>
		      	<td><%= s.id %></td>
		      	<td><%= s.nombre %></td>
		      	<td><%= s.calle %></td>
		      	<td><%= s.cp %></td>
		      	<td><%= s.pais %></td>
		      	<td><%= s.ciudad %></td>
		      	<td><%= link_to "Ver", controller: "sucursales",  action: "show", id: s.id  %></td>
		      	<td><%= link_to "Editar", controller: "sucursales", action: "edit", id: s.id  %></td>
		      	<td><%= link_to "Eliminar", sucursale_path(s.id), method: :delete, data: {confirm: "Estas seguro?"}  %></td>
		      </tr>
		    <% end %>
	    </table>
    <% else %>
    	<h2>No hay sucursales.</h2>
    <% end %>

    <%= will_paginate @sucursal %>

</div>

app/views/sucursales/new.html.erb
<h1>Crear nueva sucursal</h1>

<div class="container">
<%= form_for @sucursal, url: {action: "create"}, html: {class: ""} do |s| %>
	<% if @sucursal.errors.any? %>
		<div id="error_explanation">
		<h3>
			<%= pluralize(@sucursal.errors.count, "error") %> no permitieron que se actualizara la informacion:
		</h3>
		<ul>
			<% @sucursal.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
		</div>
	<% end %>
	<div class="row">
		<div class="col-md-6">
			<!-- Plantilla sucursal -->
			<table class='table table-condensed tablaX'>
				<tr>	
					<th>Nombre</th>
					<td><%= s.text_field :nombre ,class: 'form-control' %></td>
				</tr>
				<tr>	
					<th>Calle</th>
					<td><%= s.text_field :calle ,class: 'form-control' %></td>
				</tr>
				<tr>	
					<th>Colonia</th>
					<td><%= s.text_field :colonia ,class: 'form-control' %></td>
				</tr>
				<tr>	
					<th>Num. Ext.</th>
					<td><%= s.number_field :numExt ,class: 'form-control' , :value => 0  %></td>
				</tr>
				<tr>	
					<th>Num. Int.</th>
					<td><%= s.number_field :numInt ,class: 'form-control' , :value => 0  %></td>
				</tr>
				<tr>	
					<th>C.P.</th>
					<td><%= s.number_field :cp ,class: 'form-control', :value => 0  %></td>
				</tr>
				<tr>	
					<th>Pais</th>
					<td><%= s.text_field :pais ,class: 'form-control' %></td>
				</tr>
				<tr>	
					<th>Ciudad</th>
					<td><%= s.text_field :ciudad ,class: 'form-control' %></td>
				</tr>
			</table>
		</div>
		<div class="col-md-6" id="empleados">
				<!-- Plantilla empleados -->
			<%= s.nested_fields_for :empleados do |e| %>
				<%= e.remove_nested_fields_link 'x', class: 'btn btn-danger btn-xs pull-right', role: 'button' %>
				<table class='table table-condensed tablaX'>
					<tr>	
						<th>Nombre</th>
						<td><%= e.text_field :nombre ,class: 'form-control' %></td>
					</tr>
					<tr>	
						<th>RFC</th>
						<td><%= e.text_field :rfc ,class: 'form-control' %></td>
					</tr>
					<tr>	
						<th>Puesto</th>
						<td><%= e.text_field :puesto ,class: 'form-control' %></td>
					</tr>
				</table>
			<% end %>
				<div id="empleadosLista"></div>
				<center>
					<%= s.add_nested_fields_link :empleados, 'Agregar Empleado', data: { insert_into: 'empleadosLista' }, class: 'btn btn-primary', id:'addNueva', role: 'button' %>
				</center>
		</div>
		<input id="fieldsActivos" type="text" hidden>
	</div>

<%= s.submit %>

<% end %>
</div>

app/views/sucursales/show.html.erb
<div class="row">
	<div class="col-md-6">
		<p>
			<h2><%= @sucursal.nombre %></h2>
		</p>
		<table class='table'>
			<tr>	
				<th>Nombre</th>
				<td><%= @sucursal.nombre %></td>
			</tr>
			<tr>	
				<th>Calle</th>
				<td><%= @sucursal.calle %></td>
			</tr>
			<tr>	
				<th>Colonia</th>
				<td><%= @sucursal.colonia %></td>
			</tr>
			<tr>	
				<th>Num. Ext.</th>
				<td><%= @sucursal.numExt %></td>
			</tr>
			<tr>	
				<th>Num. Int.</th>
				<td><%= @sucursal.numInt %></td>
			</tr>
			<tr>	
				<th>C.P.</th>
				<td><%= @sucursal.cp %></td>
			</tr>
			<tr>	
				<th>Pais</th>
				<td><%= @sucursal.pais %></td>
			</tr>
			<tr>	
				<th>Ciudad</th>
				<td><%= @sucursal.ciudad %></td>
			</tr>
		</table>
		<%= link_to "Editar", edit_sucursale_path, action:'update' ,id: "news", class: "btn btn-info btn-xs pull-right" %>
	</div>
	<div class="col-md-6">
		<p>
			<h2>Empleados de sucursal</h2>
		</p>
		<% if @empleados.length < 5 %>
			<%= link_to "Agregar empleado", new_empleado_path, action:'new' ,id: @sucursal.id, class: "btn btn-info btn-xs pull-right botonAgregarEmpleado" %>
		<% end %>
		<% if @empleados.length != 0 %>
			<table class='table table-hover table-striped tablaEmpleados'>
				<tr>
					<th>Nombre</th>
					<th>RFC</th>
					<th>Puesto</th>
					<th></th>
					<th></th>
				</tr>
			<% @empleados.each do |e|  %>
				<tr class='active'>
					<td><%= e.nombre %></td>
					<td><%= e.rfc %></td>
					<td><%= e.puesto %></td>
					<td>
						<%= link_to  edit_empleado_path(e.id), class: "btn btn-info btn-xs pull-right" do %>
							<i class="glyphicon glyphicon-pencil"></i>
						<% end %>
					</td>
					<td>
						<%= link_to  empleado_path(e.id), method: :delete, class: "btn btn-danger btn-xs pull-right" do %>
							<i class="glyphicon glyphicon-remove"></i>
						<% end %>

					</td>
				</tr>
			<% end %>
			</table>
		<% else %>	
			<h2>Sin empleados</h2>
		<% end %>
		
	</div>
</div>